SELECT * FROM EMPLOYEE WHERE DEPT_ID IS NULL OR DEPT_ID=10 ORDER BY [NAME],POISITION DESC;
SELECT SUM(SALARY) FROM EMPLOYEE WHERE DEPT_ID=20;
SELECT POSITION FROM EMPLOYEE GROUP BY POSITION HAVING AVG(SALARY) > 2000;
SELECT MIN(DATE_OF_EMPLOYMENT) FROM EMPLOYEE WHERE POSITION="SALESMAN";
SELECT ID,[NAME],POSITION FROM EMPLOYEE WHERE [NAME] LIKE 'S%';
SELECT * FROM EMPLOEE LEFT JOIN DEPARTMENT ON EMPLOYEE.DEPT_ID = DEPARTMENT.ID WHERE DEPARTMENT.[NAME]="RESEARCH" ORDER BY SALARY DESC;
SELECT MAX(SALARY) - MIN(SALARY) DIFFERENCE FROM EMPLOYEE;